name: Publish Homebrew Bottle

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish-homebrew:
    runs-on: macos-latest

    steps:
      # 1. Download the ai‑commit binary asset attached by release.yml
      - name: Download release asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ASSET_URL=$(gh api repos/${{ github.repository }}/releases/${{ github.event.release.id }} \
                       --jq '.assets[] | select(.name=="ai-commit") | .url')
          gh api -H "Accept: application/octet-stream" "$ASSET_URL" > ai-commit
          chmod +x ai-commit
          tar -czf ai-commit-macos-universal.tar.gz ai-commit

      # 2. Compute SHA‑256 of bottled tarball
      - name: Compute SHA256
        id: sha
        run: echo "sha=$(shasum -a 256 ai-commit-macos-universal.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT

      # 3. Upload bottled tarball back to the release (optional)
      - name: Upload bottled tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ai-commit-macos-universal.tar.gz
          asset_name: ai-commit-macos-universal.tar.gz
          asset_content_type: application/gzip

      # 4. Clone the Homebrew tap repo
      - name: Checkout tap
        uses: actions/checkout@v3
        with:
          repository: anton-kochev/homebrew-ai-commit  # <= replace
          token: ${{ secrets.HOMEBREW_TAP_PAT }}
          path: tap

      # 5. Update formula and push only if it changed
      - name: Update formula
        working-directory: tap
        run: |
          FORMULA="Formula/ai-commit.rb"
          TAG="${{ github.event.release.tag_name }}"
          URL="https://github.com/${{ github.repository }}/releases/download/${TAG}/ai-commit-macos-universal.tar.gz"
          SHA="${{ steps.sha.outputs.sha }}"

          # Replace url and sha256 irrespective of leading spaces
          sed -i '' -E "s|^\s*url\s+\".*\"|  url \"${URL}\"|" "$FORMULA"
          sed -i '' -E "s|^\s*sha256\s+\"[a-f0-9]+\"|  sha256 \"${SHA}\"|" "$FORMULA"
          # bump version if present
          if grep -qE "^\s*version\s+\".*\"" "$FORMULA"; then
            sed -i '' -E "s|^\s*version\s+\".*\"|  version \"${TAG#v}\"|" "$FORMULA"
          fi

          if git diff --quiet; then
            echo "Formula already up to date—nothing to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add "$FORMULA"
            git commit -m "ai-commit ${TAG} (automated)"
            git push
          fi
