name: Build and Release
on:
  push:
    tags:
      - 'v*.*.*'


permissions:
  contents: write

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Rust toolchain
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Cache Cargo dependencies
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Build the application
      - name: Build
        run: cargo build --release

      # Archive the binary
      - name: Archive binary
        run: |
          mkdir -p dist
          cp target/release/ai-commit dist/
        # Replace <your-binary-name> with the name of your Rust binary

      # Create a release and upload the binary
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/ai-commit
          asset_name: ai-commit
          asset_content_type: application/octet-stream
