name: Build and Release

# Trigger only when a version tag like v1.2.3 is pushed
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Rust toolchain
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Cache Cargo dependencies
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Build the application
      - name: Build
        run: cargo build --release

      # Archive the binary
      - name: Archive binary
        run: |
          mkdir -p dist
          cp target/release/ai-commit dist/

      # Create or update the GitHub Release for this tag
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT || secrets.GITHUB_TOKEN }}

      # Upload the Rust binary as a release asset
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: ${{ steps.create_release.outputs.upload_url }}
        with:
          files: dist/ai-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT || secrets.GITHUB_TOKEN }}
